"""
Write VASP input files (POSCAR, INCAR, KPOINTS, POTCAR) to an output directory.

The Rust TUI collects all parameters (preset + user edits) and passes
them here as a single dict. This module does not load presets — it only
writes what it is told to write.
"""

import os
import tempfile
import shutil

from ase.io.vasp import write_vasp

from vaspsetup_core import WriteError
from vaspsetup_core.io import read_structure


# Keys in the params dict that are VASPSetup-internal, not INCAR parameters.
# Note: GGA is a valid INCAR tag and is NOT filtered.
_NON_INCAR_KEYS = frozenset({"pp", "kpts"})


def write_vasp_inputs(poscar_path, output_dir, params, kpts=(1, 1, 1)):
    """
    Write POSCAR, INCAR, KPOINTS, and POTCAR to output_dir.

    Uses atomic writes: files are written to a temp directory on the
    same filesystem as output_dir, then copied into place. If any file
    fails, no partial output remains.

    POTCAR is generated by concatenating per-species files from
    $VASP_PP_PATH. If VASP_PP_PATH is not set, POTCAR is skipped.

    Args:
        poscar_path: Path to input structure file
        output_dir: Directory to write VASP files into
        params: Dict of INCAR parameters
        kpts: Tuple of 3 ints for KPOINTS mesh

    Returns:
        dict with files_written list and output_dir
    """
    atoms = read_structure(poscar_path)

    # Create output_dir first so temp dir is on the same filesystem
    os.makedirs(output_dir, exist_ok=True)
    tmp_dir = tempfile.mkdtemp(prefix="vaspsetup_", dir=output_dir)

    files_written = ["POSCAR", "INCAR", "KPOINTS"]

    try:
        _write_poscar(atoms, tmp_dir)
        _write_incar(params, tmp_dir)
        _write_kpoints(kpts, tmp_dir)

        # Write POTCAR if VASP_PP_PATH is available
        pp_type = params.get("pp", "pbe")
        potcar_written = _write_potcar(atoms, tmp_dir, pp_type)
        if potcar_written:
            files_written.append("POTCAR")

        # All files written successfully — copy to final location
        for filename in files_written:
            src = os.path.join(tmp_dir, filename)
            dst = os.path.join(output_dir, filename)
            shutil.copy2(src, dst)

    except WriteError:
        raise
    except Exception as exc:
        # Clean up any files that may have been copied to output_dir
        for filename in files_written:
            dst = os.path.join(output_dir, filename)
            if os.path.isfile(dst):
                os.remove(dst)
        raise WriteError(f"Failed to write VASP input files: {exc}") from exc
    finally:
        shutil.rmtree(tmp_dir, ignore_errors=True)

    return {
        "files_written": files_written,
        "output_dir": os.path.abspath(output_dir),
    }


def _write_poscar(atoms, directory):
    """Write POSCAR from ASE Atoms object. Sorts by species for VASP compatibility."""
    path = os.path.join(directory, "POSCAR")
    write_vasp(path, atoms, direct=True, sort=True)


def _write_incar(params, directory):
    """Write INCAR from parameter dict."""
    path = os.path.join(directory, "INCAR")
    with open(path, "w", encoding="utf-8") as f:
        f.write("# INCAR generated by VASPSetup\n")
        for key in sorted(params):
            if key in _NON_INCAR_KEYS:
                continue
            val = params[key]
            if isinstance(val, bool):
                val = ".TRUE." if val else ".FALSE."
            elif isinstance(val, (list, tuple)):
                val = "  ".join(str(v) for v in val)
            f.write(f"{key} = {val}\n")


def _write_potcar(atoms, directory, pp_type="pbe"):
    """Write POTCAR by concatenating per-species files from VASP_PP_PATH.

    Uses ASE's Vasp calculator which handles setups, suffixes, and
    compressed (.Z) files automatically. Species order matches POSCAR
    (atoms are sorted by species before both POSCAR and POTCAR are written).

    Returns True if POTCAR was written, False if VASP_PP_PATH is not set.
    Raises WriteError if VASP_PP_PATH is set but a species POTCAR is missing.
    """
    if not os.environ.get("VASP_PP_PATH"):
        return False

    try:
        from ase.calculators.vasp import Vasp
        # Use the output directory to avoid CWD conflicts when
        # multiple parallel jobs create Vasp calculator instances.
        calc = Vasp(pp=pp_type, directory=directory)
        calc.initialize(atoms)
        calc.write_potcar(directory=directory)
    except Exception as exc:
        raise WriteError(f"Failed to write POTCAR: {exc}") from exc

    return True


def _write_kpoints(kpts, directory):
    """Write KPOINTS file with Gamma-centered mesh."""
    path = os.path.join(directory, "KPOINTS")
    with open(path, "w", encoding="utf-8") as f:
        f.write("Automatic mesh\n")
        f.write("0\n")
        f.write("Gamma\n")
        f.write(f"  {kpts[0]}  {kpts[1]}  {kpts[2]}\n")
        f.write("  0  0  0\n")
